### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by domingoruiz** [navy-linux/navylinux.org#1]
@navylinux Hi. Why have you invited me? You can give me more information by email to decide whether to join the project or not. Thank you. ordenadordomi@gmail.com

**Comment by navylinux** [comment]
Hi, 

Thanks for your reply, we have seen your experience and invited you. 

Navy Linux is a recompilation of the Red Hat Linux project just as the CentOS Linux project has been for all these years. 


Read here [ https://github.com/navy-linux/navy | https://github.com/navy-linux/navy ]
