### ISSUE TITLE
Starting hugo server on Ubuntu 20.04

### ISSUE THREAD

**Issue by BasilioDavid** [navy-linux/navylinux.org#12]
After run: "npm install" in the navylinux.org folder
and then run "hugo server", hugo throw the following error:

> Start building sites … 
> Built in 31 ms
> Error: Error building site: TOCSS: failed to transform "scss/app.scss" (text/x-scss): SCSS processing failed: file "stdin", line 2, col 1: File to import not found or unreadable: bootstrap/scss/functions. 

**S.O Description**

> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.1 LTS
> Release:	20.04
> Codename:	focal

**Comment by domingoruiz** [comment]
Can you check if it already works with the code of the dev branch? Thank you. Let me know if it works to close the issue.

**Comment by BasilioDavid** [comment]
Yess, its working now!!
